const reply=(statusCode,body)=>({statusCode,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'POST, OPTIONS'},body:JSON.stringify(body)});
const clean=v=>String(v??'').trim();
const esc=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
exports.handler=async event=>{
  if(event.httpMethod==='OPTIONS')return reply(200,{ok:true});if(event.httpMethod!=='POST')return reply(405,{ok:false,error:'Método no permitido'});
  const url=clean(process.env.SUPPORT_SUPABASE_URL||process.env.SUPABASE_URL).replace(/\/$/,'');const key=clean(process.env.SUPPORT_SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY);
  if(!url||!key)return reply(501,{ok:false,error:'Faltan las variables de Supabase de Soporte en Netlify'});
  try{
    const token=clean(event.headers.authorization||event.headers.Authorization).replace(/^Bearer\s+/i,'');if(!token)return reply(401,{ok:false,error:'Sesión requerida'});
    const ur=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${token}`}});const user=await ur.json().catch(()=>({}));if(!ur.ok||!user.email)return reply(401,{ok:false,error:'Sesión inválida'});
    const h={apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};const req=async(path,options={})=>{const r=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{...h,...(options.headers||{})}});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||`Error ${r.status}`);return d};
    const profiles=await req(`service_users?select=*&email=ilike.${encodeURIComponent(user.email)}&limit=1`);const profile=profiles?.[0];if(!profile||profile.activo===false)return reply(403,{ok:false,error:'Usuario de soporte no autorizado'});
    const body=JSON.parse(event.body||'{}');if(clean(body.action)!=='notify_client')return reply(400,{ok:false,error:'Acción no válida'});
    const rows=await req(`service_orders?select=*&id=eq.${encodeURIComponent(clean(body.order_id))}&limit=1`);const o=rows?.[0];if(!o)return reply(404,{ok:false,error:'Orden no encontrada'});if(!o.client_email)return reply(400,{ok:false,error:'La orden no tiene correo del cliente'});
    const resend=clean(process.env.RESEND_API_KEY||process.env.RESEND_APY_KEY);if(!resend)return reply(501,{ok:false,error:'Falta RESEND_API_KEY en el sitio de Soporte'});
    const q=new URLSearchParams({orden:String(o.code)});if(o.public_token)q.set('token',String(o.public_token));
    const site=clean(process.env.URL||process.env.DEPLOY_PRIME_URL||'https://thinkstore.com.ve').replace(/\/$/,'');const supportBase=clean(process.env.SUPPORT_PUBLIC_URL||process.env.SOPORTE_PUBLIC_URL||`${site}/soporte`).replace(/\/$/,'');
    const tracking=`${supportBase}/seguimiento.html?${q.toString()}`;
    const isQuote=String(o.status||'')==='Cotización enviada'||String(o.quote_status||'')==='Enviado';
    const subject=isQuote?`Tu cotización está lista · ${o.code}`:`Actualización de tu reparación · ${o.code}`;
    const logo=`${supportBase}/assets/thinkstore-logo-white.png`;
    const html=`<!doctype html><html><body style="margin:0;background:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;color:#1d1d1f"><div style="padding:38px 16px"><div style="max-width:620px;margin:0 auto;background:#fff;border:1px solid #e8e8ed;border-radius:28px;overflow:hidden"><div style="background:#0b0b0d;padding:28px 34px;text-align:center"><img src="${logo}" alt="ThinkStore" width="190" style="display:block;width:190px;max-width:80%;height:auto;margin:0 auto"></div><div style="padding:42px 38px 38px;text-align:center"><div style="font-size:13px;color:#86868b;margin-bottom:12px">${esc(o.code)} · ${esc(o.device_model||'Equipo')}</div><h1 style="font-size:30px;line-height:1.08;letter-spacing:-.035em;margin:0 0 14px">${isQuote?'Tu cotización está lista.':'Tu reparación tiene una actualización.'}</h1><p style="max-width:470px;margin:0 auto;color:#6e6e73;font-size:16px;line-height:1.55">${isQuote?`Hola ${esc(o.client_name)}. Revisa la reparación propuesta y apruébala cuando estés de acuerdo.`:`Hola ${esc(o.client_name)}. El estado de tu equipo ahora es <b style="color:#1d1d1f">${esc(o.status)}</b>.`}</p><div style="margin-top:30px"><a href="${tracking}" style="display:inline-block;background:#0071e3;color:#fff;text-decoration:none;border-radius:999px;padding:14px 24px;font-size:15px;font-weight:700">${isQuote?'Revisar cotización':'Ver seguimiento'}</a></div><p style="margin:30px 0 0;color:#a1a1a6;font-size:11px;line-height:1.5">En el seguimiento puedes revisar el diagnóstico, bitácora, fotografías y mensajes de nuestro equipo técnico.</p></div></div><div style="text-align:center;color:#a1a1a6;font-size:10px;margin-top:16px">ThinkStore · Servicio Técnico</div></div></body></html>`;
    const text=isQuote?`ThinkStore Soporte\n\nHola ${o.client_name}. Tu cotización para la orden ${o.code} está lista.\n\nRevisar y aprobar: ${tracking}`:`ThinkStore Soporte\n\nHola ${o.client_name}. Tu orden ${o.code} ahora está en estado: ${o.status}.\n\nVer seguimiento: ${tracking}`;
    const er=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${resend}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.FROM_SOPORTE_EMAIL||process.env.FROM_EMAIL||'ThinkStore Soporte <soporte@thinkstore.com.ve>',to:o.client_email,reply_to:process.env.REPLY_TO_SOPORTE||'soporte@thinkstore.com.ve',subject,html,text})});const ed=await er.json().catch(()=>({}));if(!er.ok)throw new Error(ed.message||'Error enviando correo');
    await req('service_audit_log',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({actor_email:user.email,actor_role:profile.rol,action:'notify_client',entity_type:'service_order',entity_id:String(o.id),after_data:{recipient:o.client_email,provider_id:ed.id||null,status:o.status}})});
    return reply(200,{ok:true,email:{sent:true,id:ed.id||null}});
  }catch(error){console.error('Support actions',error);return reply(500,{ok:false,error:error.message||'Error interno'})}
};
