-- ThinkStore V13.54 · Historial de campañas
create table if not exists public.marketing_campaigns (
  id bigint generated by default as identity primary key,
  subject text not null,
  title text,
  subtitle text,
  audience text,
  recipients_count integer not null default 0,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  banner_url text,
  content_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.marketing_campaigns add column if not exists subtitle text;
alter table public.marketing_campaigns add column if not exists banner_url text;
alter table public.marketing_campaigns add column if not exists content_json jsonb not null default '{}'::jsonb;

create index if not exists marketing_campaigns_created_at_idx on public.marketing_campaigns(created_at desc);

alter table public.marketing_campaigns enable row level security;
-- El panel accede a esta tabla únicamente mediante funciones Netlify autenticadas con service role.
