// Node-only integration harness: real app functions, in-memory Supabase and a minimal DOM.
// Does not contact production. Browser layout and live RLS require separate validation.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../soporte/app.js'),'utf8');
function setup(){
  const db={service_orders:[],service_order_notes:[],service_order_photos:[]},calls=[],nodes={},state={failPhotos:false,failInsert:false};
  function element(id){return nodes[id]??={id,value:'',textContent:'',dataset:{},files:[],hidden:false,disabled:false,readOnly:false,style:{},classList:{values:new Set(),add(v){this.values.add(v)},remove(v){this.values.delete(v)},contains(v){return this.values.has(v)},toggle(){}},innerHTML:'',closest(){return {hidden:false}},setAttribute(k,v){this[k]=v},removeAttribute(k){delete this[k]},querySelectorAll(){return []},querySelector(){return {reportValidity:()=>true,reset(){},requestSubmit(){}}},addEventListener(){},replaceChildren(){},append(){},focus(){},showModal(){this.open=true},close(){this.open=false}};}
  for(const [,id] of fs.readFileSync(path.join(__dirname,'../soporte/panel.html'),'utf8').matchAll(/id="([^"]+)"/g))element(id);
  const checklist=[{childNodes:[{}, {textContent:'Pantalla'}],textContent:'Pantalla',querySelector:q=>q.startsWith('input')?{checked:true}:{value:'Funciona',options:[{value:'Funciona'}]}}];
  const client={auth:{getSession:()=>new Promise(()=>{})},storage:{from:bucket=>({upload:async(p,f)=>{calls.push({bucket,path:p,file:f});return {error:state.failPhotos?{message:'storage offline'}:null}},remove:async()=>({}),createSignedUrl:async()=>({data:{signedUrl:'private-url'}})})},from(table){let action='select',payload,filter;const q={select(){return q},order(){return q},limit(){return q},eq(k,v){filter=[k,v];return q},insert(row){action='insert';payload=row;return q},upsert(row){action='insert';payload=row;return q},update(row){action='update';payload=row;return q},single(){return q.then(r=>({...r,data:r.data?.[0]}))},then(resolve,reject){if(state.failAccess&&table==='service_order_access')return Promise.resolve({error:{message:'access failure'}}).then(resolve,reject);if(state.failInsert&&table==='service_orders'&&action==='insert')return Promise.resolve({error:{message:'insert failure'}}).then(resolve,reject);let data=db[table]||[];if(action==='insert'){const row={id:'id-'+(db[table]?.length||0),created_at:'2026-09-30',...structuredClone(payload)};(db[table]??=[]).push(row);data=[row];calls.push({table,action,payload:structuredClone(payload)});}else if(action==='update'){data=data.filter(r=>!filter||r[filter[0]]===filter[1]);data.forEach(r=>Object.assign(r,structuredClone(payload)));calls.push({table,action,payload:structuredClone(payload)});}else if(filter)data=data.filter(r=>r[filter[0]]===filter[1]);return Promise.resolve({data,error:null}).then(resolve,reject);}};return q;}};
  const draftData=new Map();
  const indexedDB={open(){const req={};queueMicrotask(()=>{req.result={close(){},transaction(){const tx={};tx.objectStore=()=>({get(k){const op={result:draftData.get(k)};queueMicrotask(()=>tx.oncomplete());return op;},put(v,k){draftData.set(k,structuredClone(v));queueMicrotask(()=>tx.oncomplete());return {};},delete(k){draftData.delete(k);queueMicrotask(()=>tx.oncomplete());return {};}});return tx;}};req.onsuccess();});return req;}};
  nodes.orderModal.querySelectorAll=()=>Object.values(nodes).filter(n=>/^o[A-Z]|^rx(Type|Platform|Condition|Diagnosis)$|^sig/.test(n.id));
  const context={...nodes,indexedDB,console,URL,Date,Map,Set,Promise,crypto:require('node:crypto').webcrypto,location:{href:'https://test.invalid/panel.html',pathname:'/panel.html',hash:'',origin:'https://test.invalid'},localStorage:{getItem:()=>JSON.stringify({email:'test@example.test',role:'admin',name:'Test'}),setItem(){},removeItem(){}},document:{createElement:tag=>element(tag+Math.random()),getElementById:element,addEventListener(){},querySelectorAll:q=>q==='#receptionChecklist label'?checklist:[],querySelector:()=>({reportValidity:()=>true,reset(){}}),body:{classList:{add(){},remove(){},contains:()=>true},appendChild(){}}},alert:m=>calls.push({alert:m}),confirm:()=>true,requestAnimationFrame:f=>f(),setTimeout:()=>0,clearTimeout(){}};
  context.window={supabase:{createClient:()=>client},open:()=>({closed:false,close(){this.closed=true;calls.push({popupClosed:true})},document:{open(){},write:s=>calls.push({print:s}),close(){}}})};
  vm.createContext(context);
  const exposed=source.replace('return{toggleDeviceAccess,','return{test:{renderReceptionModels,closeReceptionModels,chooseReceptionModel,mapOrder,receptionMeta,inspectionAreas,receptionDetails,storeOrderFile,finishReceptionFiles,trackingUrl,printReceptionSheetByOrder,printDeviceLabelByOrder,loadSupportData,restoreReceptionV2, setState(s){if(s.category)receptionCategory=s.category;if(s.orderId!==undefined)activeReceptionOrderId=s.orderId;if(s.photos)receptionPhotos=s.photos;if(s.orders)orders=s.orders;if(s.role)session.role=s.role;if(s.marks)damageMarks=s.marks;}, getState(){return {receptionPhotos,activeReceptionOrderId,damageMarks}}, confirm(){receptionConfirmed=true;}},setReceptionCategory,');
  vm.runInContext(exposed+'\nglobalThis.api=TSService;',context);
  // Skip unrelated dashboard rendering while keeping loading, persistence, printing and permission logic real.
  vm.runInContext('',context);
  for(const [id,v] of Object.entries({oClient:'Test client',oPhone:'04140000000',oDevice:'iPhone 16',oIssue:'No enciende',oPriority:'Normal',oBrand:'Apple',oPasswordFlag:'No',rxType:'Teléfono',rxPlatform:'PlayStation',rxCondition:'Bueno',oSerial:'SERIAL',oAccessories:'Cable',oCategory:'iPhone'}))element(id).value=v;
  const api=context.api;
  return {api,db,calls,nodes,state,context,draftData,async save(){api.test.confirm();await api.saveOrder({preventDefault(){}});}};
}
test('Apple saves original fields and additive metadata; QR and print share the order',async()=>{
 const h=setup();h.api.test.setState({marks:[{x:12,y:20,type:'rayon',view:'front'}]});h.nodes.oVisual.value='1. rayon [front] en X:12.0 Y:20.0';await h.save();
 assert.doesNotMatch(h.nodes.serviceToast?.textContent||'',/No se pudo completar/);assert.equal(h.db.service_orders.length,1);const row=h.db.service_orders[0];assert.equal(row.device_type,'iPhone');assert.equal(row.reception_checklist.Pantalla.value,'Funciona');assert.equal(row.reception_checklist.__reception_v2.device_category,'apple');assert.equal(row.reception_checklist.__reception_v2.damage_marks.length,1);
 const o=h.api.test.mapOrder(row);assert.equal(o.deviceCategory,'apple');assert.match(h.api.test.trackingUrl(o),/https:\/\/soporte.thinkstore.com.ve\/seguimiento.html\?orden=TS-SVC-/);h.api.test.printReceptionSheetByOrder(o);h.api.test.printDeviceLabelByOrder(o);assert.equal(h.calls.filter(x=>x.print).length,2);assert.match(h.calls.find(x=>x.print).print,/assets\/thinkstore-logo-print\.png/);assert.doesNotMatch(h.calls.find(x=>x.print).print,/<div class="logo">TS<\/div>/);assert.ok(h.db.service_order_notes.length);assert.ok(h.db.service_audit_log.length);
});
test('Manual other device uses the same service_orders payload',async()=>{const h=setup();h.api.test.setState({category:'other'});h.nodes.oDevice.value='Modelo manual';h.nodes.oBrand.value='Marca manual';h.nodes.rxType.value='Laptop';h.nodes.rxDiagnosis.value='Revisar teclado';assert.deepEqual(Array.from(h.api.test.inspectionAreas()),['Pantalla','Teclado','Tapa','Base','Puertos']);await h.save();const row=h.db.service_orders[0];assert.equal(row.device_type,'Laptop');assert.equal(row.reception_checklist.__reception_v2.brand,'Marca manual');assert.equal(row.reception_checklist.__reception_v2.diagnosis,'Revisar teclado');});
test('Gaming platform, console and controller inspection',async()=>{const h=setup();h.api.test.setState({category:'gaming'});h.nodes.oDevice.value='DualSense';h.nodes.rxType.value='Control / mando';assert.ok(h.api.test.inspectionAreas().includes('Joysticks'));await h.save();assert.equal(h.db.service_orders[0].reception_checklist.__reception_v2.platform,'PlayStation');h.nodes.rxType.value='Consola';assert.ok(h.api.test.inspectionAreas().includes('Posterior'));});
test('Legacy rows fall back to Apple and retain old visual marks',()=>{const h=setup();const o=h.api.test.mapOrder({id:'legacy',device_model:'iPhone 16',visual_condition:'1. rayon [front] en X:12.0 Y:20.0',reception_checklist:{Custom:{checked:true,value:'OK'}}});assert.equal(o.deviceCategory,'apple');h.api.test.restoreReceptionV2(o);assert.equal(h.nodes.oVisual.value,o.visual);assert.equal(h.api.test.getState().damageMarks.length,1);});
test('Editing reception does not overwrite current workflow status or unknown checklist fields',async()=>{const h=setup();const row={id:'existing',code:'TS-SVC-2026-0001',device_model:'iPhone 16',status:'En reparación',reception_checklist:{Custom:{checked:true,value:'OK'}}};h.db.service_orders.push(row);const o=h.api.test.mapOrder({...row,status:'Recibido'});h.api.test.setState({orderId:row.id,orders:[o]});h.api.test.restoreReceptionV2(o);await h.save();assert.equal(row.status,'En reparación');assert.equal(row.reception_checklist.Custom.value,'OK');assert.ok(!('status' in h.calls.find(x=>x.table==='service_orders'&&x.action==='update').payload));assert.equal(h.db.service_orders.length,1);});
test('Failed photos remain queued and retries update the same order',async()=>{const h=setup();h.api.test.setState({category:'gaming',photos:[new File(['photo'],'photo.png',{type:'image/png'})]});h.state.failPhotos=true;await h.save();assert.equal(h.db.service_orders.length,1);assert.equal(h.api.test.getState().receptionPhotos.length,1);h.state.failPhotos=false;await h.save();assert.equal(h.db.service_orders.length,1);assert.equal(h.db.service_order_photos.length,1);assert.equal(h.db.service_order_photos[0].file_url,'private');assert.equal(h.api.test.getState().receptionPhotos.length,0);assert.equal(h.calls.find(x=>x.bucket).bucket,'service-order-files');});
test('Save requires review, permission and successful insert',async()=>{const h=setup();await h.api.saveOrder({preventDefault(){}});assert.equal(h.db.service_orders.length,0);assert.equal(h.nodes.rxReview.open,true);h.api.test.setState({role:'client'});await h.save();assert.equal(h.db.service_orders.length,0);h.api.test.setState({role:'admin'});h.state.failInsert=true;await h.save();assert.equal(h.db.service_orders.length,0);assert.equal(h.nodes.oClient.value,'Test client');});

test('Draft saves without creating an order and restores category, manual fields and diagnosis',async()=>{const h=setup();h.api.test.setState({category:'other'});h.nodes.oDevice.value='Manual laptop';h.nodes.oBrand.value='Custom';h.nodes.rxType.value='Laptop';h.nodes.rxDiagnosis.value='Keyboard issue';await h.api.saveReceptionDraft();assert.equal(h.db.service_orders.length,0);h.nodes.oDevice.value='Changed';await h.api.restoreReceptionDraft();assert.equal(h.nodes.oDevice.value,'Manual laptop',h.nodes.serviceToast?.textContent);assert.equal(h.nodes.oBrand.value,'Custom');assert.equal(h.nodes.rxDiagnosis.value,'Keyboard issue');assert.equal(h.api.test.receptionDetails().device_category,'other');});

test('client document/address persist and print, device access stays outside order and audit',async()=>{const h=setup();h.nodes.oDocument.value='V-123456';h.nodes.oAddress.value='Caracas';h.nodes.oAccessCode.value='secret-test-123';await h.save();const row=h.db.service_orders[0];assert.equal(row.reception_checklist.__reception_v2.client_document,'V-123456');assert.equal(row.reception_checklist.__reception_v2.client_address,'Caracas');assert.equal(row.password_received,true);assert.equal(h.db.service_order_access[0].access_code,'secret-test-123');assert.ok(!JSON.stringify(h.db.service_orders).includes('secret-test-123'));assert.ok(!JSON.stringify(h.db.service_audit_log).includes('secret-test-123'));h.api.test.printReceptionSheetByOrder(h.api.test.mapOrder(row));const html=h.calls.find(c=>c.print).print;assert.match(html,/V-123456/);assert.match(html,/Caracas/);assert.ok(!html.includes('secret-test-123'));});
test('device access failure retains order identity for safe retry',async()=>{const h=setup();h.nodes.oAccessCode.value='internal-only';h.state.failAccess=true;await h.save();assert.equal(h.db.service_orders.length,1);assert.equal(h.nodes.oAccessCode.value,'internal-only');h.state.failAccess=false;await h.save();assert.equal(h.db.service_orders.length,1);assert.equal(h.db.service_order_access[0].access_code,'internal-only');});
test('draft deliberately excludes the device access code',async()=>{const h=setup();h.nodes.oAccessCode.value='do-not-cache';h.nodes.oDocument.value='V-987';await h.api.saveReceptionDraft();const d=h.draftData.get('test@example.test');assert.equal(d.fields.oDocument,'V-987');assert.ok(!('oAccessCode' in d.fields));assert.ok(!JSON.stringify(d).includes('do-not-cache'));});
test('model picker lists full catalog, filters and closes accessibly',()=>{const h=setup();h.nodes.oCategory.value='';h.api.test.renderReceptionModels('');assert.match(h.nodes.rxModelList.innerHTML,/iPhone X/);assert.match(h.nodes.rxModelList.innerHTML,/MacBook/);assert.equal(h.nodes.deviceModelSearch['aria-expanded'],'true');h.api.test.renderReceptionModels('iPhone X');assert.match(h.nodes.rxModelList.innerHTML,/iPhone X/);assert.doesNotMatch(h.nodes.rxModelList.innerHTML,/MacBook/);h.api.test.closeReceptionModels();assert.equal(h.nodes.rxModelList.inert,true);assert.equal(h.nodes.deviceModelSearch['aria-expanded'],'false');});

test('print on save opens prepared label only after successful persistence',async()=>{const h=setup();h.nodes.rxPrintAfterSave.checked=true;await h.save();const html=h.calls.filter(x=>x.print).map(x=>x.print);assert.equal(html.length,2);assert.match(html[0],/Guardando la orden/);assert.match(html[1],/size:40mm 60mm/);assert.match(html[1],/TS-SVC-/);assert.equal(h.calls.filter(x=>x.popupClosed).length,0);});
test('failed save closes pending print window without printing an order',async()=>{const h=setup();h.nodes.rxPrintAfterSave.checked=true;h.state.failInsert=true;await h.save();assert.equal(h.db.service_orders.length,0);assert.equal(h.calls.filter(x=>x.print).length,1);assert.equal(h.calls.filter(x=>x.popupClosed).length,1);});
