const test=require('node:test'),assert=require('node:assert/strict');
const {manage}=require('../soporte/netlify/functions/support-user-actions');
function setup(overrides={}){const calls=[];const body={action:'invite_user',email:'staff@example.test',nombre:'Staff',rol:'reception',activo:true,permissions:['reception','orders']};const opts={body,profile:{rol:'admin'},user:{email:'admin@example.test'},url:'https://supabase.test',key:'test-only',reply:(statusCode,body)=>({statusCode,body}),req:async(p,o)=>{calls.push({p,o});return o?null:[]},...overrides};return {opts,calls};}
test('receptionists cannot invite or change permissions',async()=>{const h=setup({profile:{rol:'reception'}});const r=await manage(h.opts);assert.equal(r.statusCode,403);assert.equal(h.calls.length,0);});
test('reject elevated role and invalid custom permissions before any writes',async()=>{const h=setup();h.opts.body.rol='superadmin';assert.equal((await manage(h.opts)).statusCode,400);h.opts.body.rol='technician';h.opts.body.permissions=['users'];assert.equal((await manage(h.opts)).statusCode,400);assert.equal(h.calls.length,0);});
test('protect own account and existing administrative users',async()=>{const h=setup();h.opts.body.email='admin@example.test';assert.equal((await manage(h.opts)).statusCode,403);h.opts.body.email='staff@example.test';h.opts.req=async()=>[{rol:'superadmin'}];assert.equal((await manage(h.opts)).statusCode,403);});
test('invite persists scope before sending email, audits and uses trusted redirect',async()=>{const h=setup();global.fetch=async(url,init)=>{assert.ok(h.calls.some(c=>c.o?.method==='POST'));assert.match(url,/\/auth\/v1\/invite\?redirect_to=/);assert.equal(JSON.parse(init.body).email,'staff@example.test');return {ok:true,json:async()=>({id:'new-user'})};};const r=await manage(h.opts);assert.equal(r.statusCode,200);assert.equal(r.body.invite_sent,true);const row=JSON.parse(h.calls.find(c=>c.p==='service_users').o.body);assert.deepEqual(row.permissions,['dashboard','reception','orders']);assert.ok(h.calls.some(c=>c.p==='service_audit_log'));});
test('email failure reports profile saved without claiming delivery',async()=>{global.fetch=async()=>({ok:false,json:async()=>({msg:'Email already registered'})});const h=setup();const r=await manage(h.opts);assert.equal(r.body.ok,true);assert.equal(r.body.invite_sent,false);assert.match(r.body.warning,/correo no se envió/);});
test('missing migration stops invitation and reports actionable failure',async()=>{let sent=false;global.fetch=async()=>{sent=true;};const h=setup({req:async(p,o)=>{if(o)throw Error('column permissions missing');return [];}});const r=await manage(h.opts);assert.equal(r.statusCode,400);assert.match(r.body.error,/V14.38/);assert.equal(sent,false);});
test('saving technician permissions does not send email',async()=>{global.fetch=async()=>{throw Error('must not send')};const h=setup();h.opts.body.action='save_user';h.opts.body.rol='technician';h.opts.body.permissions=['technical'];h.opts.req=async(p,o)=>{h.calls.push({p,o});return o?null:[{email:'staff@example.test',rol:'technician'}]};const r=await manage(h.opts);assert.equal(r.body.ok,true);assert.equal(r.body.invite_sent,false);assert.ok(h.calls.some(c=>c.o?.method==='PATCH'));});

test('network failure explicitly reports that profile remains saved',async()=>{global.fetch=async()=>{throw Error('network unavailable')};const h=setup();const r=await manage(h.opts);assert.equal(r.body.ok,true);assert.equal(r.body.invite_sent,false);assert.match(r.body.warning,/Usuario guardado/);});
