const test=require('node:test'),assert=require('node:assert/strict');
const {manage}=require('../soporte/netlify/functions/support-user-actions');
process.env.RESEND_API_KEY='test-only';
function setup(overrides={}){const calls=[];const body={action:'invite_user',email:'staff@example.test',nombre:'Staff',rol:'reception',activo:true,permissions:['reception','orders']};const opts={body,profile:{rol:'admin'},user:{email:'admin@example.test'},url:'https://supabase.test',key:'test-only',reply:(statusCode,body)=>({statusCode,body}),req:async(p,o)=>{calls.push({p,o});return o?null:[]},...overrides};return {opts,calls};}
test('receptionists cannot invite or change permissions',async()=>{const h=setup({profile:{rol:'reception'}});const r=await manage(h.opts);assert.equal(r.statusCode,403);assert.equal(h.calls.length,0);});
test('reject elevated role and invalid custom permissions before any writes',async()=>{const h=setup();h.opts.body.rol='superadmin';assert.equal((await manage(h.opts)).statusCode,400);h.opts.body.rol='technician';h.opts.body.permissions=['users'];assert.equal((await manage(h.opts)).statusCode,400);assert.equal(h.calls.length,0);});
test('protect own account and existing administrative users',async()=>{const h=setup();h.opts.body.email='admin@example.test';assert.equal((await manage(h.opts)).statusCode,403);h.opts.body.email='staff@example.test';h.opts.req=async()=>[{rol:'superadmin'}];assert.equal((await manage(h.opts)).statusCode,403);});
test('invite persists scope before branded email and audits without leaking the token',async()=>{const h=setup();const calls=[];global.fetch=async(url,init)=>{assert.ok(h.calls.some(c=>c.o?.method==='POST'));const body=JSON.parse(init.body);calls.push({url,body});if(url.includes('/generate_link')){assert.equal(body.type,'invite');assert.equal(body.redirect_to,'https://soporte.thinkstore.com.ve/index.html');return {ok:true,json:async()=>({action_link:'https://supabase.test/auth/v1/verify?token=secret-token&type=invite'})};}assert.equal(url,'https://api.resend.com/emails');assert.equal(body.from,'ThinkStore <info@thinkstore.com.ve>');assert.equal(body.reply_to,'info@thinkstore.com.ve');assert.deepEqual(body.to,['staff@example.test']);assert.match(body.html,/logo-thinkstore-email-transparent/);return {ok:true,json:async()=>({id:'mail-id'})};};const r=await manage(h.opts);assert.equal(r.body.invite_sent,true);assert.equal(calls.length,2);assert.ok(!JSON.stringify(h.calls).includes('secret-token'));assert.ok(!JSON.stringify(r).includes('secret-token'));});
test('email failure reports profile saved without claiming delivery',async()=>{global.fetch=async()=>({ok:false,json:async()=>({msg:'Email already registered'})});const h=setup();const r=await manage(h.opts);assert.equal(r.body.ok,true);assert.equal(r.body.invite_sent,false);assert.match(r.body.warning,/correo no se envió/);});
test('missing migration stops invitation and reports actionable failure',async()=>{let sent=false;global.fetch=async()=>{sent=true;};const h=setup({req:async(p,o)=>{if(o)throw Error('column permissions missing');return [];}});const r=await manage(h.opts);assert.equal(r.statusCode,400);assert.match(r.body.error,/V14.38/);assert.equal(sent,false);});
test('saving technician permissions does not send email',async()=>{global.fetch=async()=>{throw Error('must not send')};const h=setup();h.opts.body.action='save_user';h.opts.body.rol='technician';h.opts.body.permissions=['technical'];h.opts.req=async(p,o)=>{h.calls.push({p,o});return o?null:[{email:'staff@example.test',rol:'technician'}]};const r=await manage(h.opts);assert.equal(r.body.ok,true);assert.equal(r.body.invite_sent,false);assert.ok(h.calls.some(c=>c.o?.method==='PATCH'));});

test('network failure explicitly reports that profile remains saved',async()=>{global.fetch=async()=>{throw Error('network unavailable')};const h=setup();const r=await manage(h.opts);assert.equal(r.body.ok,true);assert.equal(r.body.invite_sent,false);assert.match(r.body.warning,/Usuario guardado/);});
test('missing email configuration does not generate a link or send mail',async()=>{const previous=process.env.RESEND_API_KEY;delete process.env.RESEND_API_KEY;let n=0;global.fetch=async()=>{n++;throw Error('unexpected')};try{const r=await manage(setup().opts);assert.equal(r.body.invite_sent,false);assert.match(r.body.warning,/RESEND_API_KEY/);assert.equal(n,0);}finally{process.env.RESEND_API_KEY=previous;}});
test('rejected provider delivery is never reported as sent',async()=>{global.fetch=async url=>url.includes('generate_link')?{ok:true,json:async()=>({action_link:'https://supabase.test/auth/v1/verify?token=test&type=invite'})}:{ok:false,json:async()=>({message:'domain not verified'})};const r=await manage(setup().opts);assert.equal(r.body.invite_sent,false);assert.match(r.body.warning,/Resend/);});
test('invitation escapes recipient content',()=>{const {template}=require('../soporte/netlify/functions/support-invitation');const html=template({name:'<script>bad</script>',role:'technician',link:'https://example.test/?a=1&b=2'});assert.ok(!html.includes('<script>'));assert.match(html,/&lt;script&gt;/);assert.match(html,/Técnico/);assert.match(html,/a=1&amp;b=2/);});
