const test=require('node:test'),assert=require('node:assert/strict'),{handle}=require('../soporte/netlify/functions/lib/workshop-core.cjs');
const env={SUPPORT_SUPABASE_URL:'https://support.test',SUPPORT_SUPABASE_SERVICE_ROLE_KEY:'support-key',SUPABASE_URL:'https://main.test',SUPABASE_SERVICE_ROLE_KEY:'main-key'};
const id='11111111-1111-4111-8111-111111111111';
function mock(role='admin',permissions=null){const calls=[];global.fetch=async(url,init={})=>{calls.push({url,init});let data=[];if(url.endsWith('/auth/v1/user'))data={id,email:'admin@test.test'};else if(url.includes('/service_users?'))data=[{rol:role,activo:true,permissions}];else if(url.includes('/profiles?'))data=[{role,active:true}];else if(url.includes('/thinkstore_inventory_users?'))data=[{role,active:true,permissions}];else if(url.includes('/service_parts?'))data=[];else if(url.includes('/rpc/'))data=id;return {ok:true,json:async()=>data};};return calls;}
const req=(action,body)=>({method:body?'POST':'GET',headers:{Authorization:'Bearer test'},action,body:body?{action,...body}:{}});
test('public catalog queries only dedicated support table with explicit safe columns',async()=>{const calls=mock();const r=await handle({method:'GET'},env,'public');assert.equal(r.status,200);assert.equal(r.body.source,'support_service_parts');assert.equal(calls.length,1);assert.match(calls[0].url,/support.test\/rest\/v1\/service_parts/);assert.doesNotMatch(calls[0].url,/unit_cost|access_code|inventory_variants/);});
test('no session and client role cannot read or mutate workshop data',async()=>{mock();assert.equal((await handle({method:'GET'},env,'support')).status,401);const calls=mock('client');assert.equal((await handle(req('parts'),env,'support')).status,403);assert.ok(!calls.some(x=>x.url.includes('/service_parts?')));});
test('custom module permissions are enforced server-side',async()=>{mock('reception',['dashboard']);assert.equal((await handle(req('finance'),env,'support')).status,403);assert.equal((await handle(req('parts'),env,'support')).status,403);});
test('admin authentication uses main project but inventory writes go to support project',async()=>{const calls=mock();const r=await handle(req('stock',{id,request_id:id,delta:2,note:'Compra'}),env,'admin');assert.equal(r.status,200);assert.ok(calls[0].url.startsWith('https://main.test/auth/'));const rpc=calls.find(c=>c.url.includes('/rpc/'));assert.ok(rpc.url.startsWith('https://support.test/'));assert.equal(JSON.parse(rpc.init.body).p_actor,'admin@test.test');});
test('inventory endpoint cannot mutate finances even for admin',async()=>{mock('super_admin');assert.equal((await handle(req('payment',{id,quote_id:id,amount:20}),env,'inventory')).status,403);});
test('stock requires idempotency key and quotes reject invalid money',async()=>{mock();assert.equal((await handle(req('stock',{id,delta:1,note:'Compra'}),env,'support')).status,400);assert.equal((await handle(req('quote',{id,client:'Test',lines:[{kind:'labor',quantity:1,unit_price:'NaN',unit_cost:0}]}),env,'support')).status,400);});
test('missing support configuration never silently falls back to main inventory',async()=>{mock();assert.equal((await handle(req('parts'),{SUPABASE_URL:env.SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY:'key'},'admin')).status,501);});

test('finance-only receptionist can read parts for quoting but cannot alter stock',async()=>{mock('reception',['finance']);assert.equal((await handle(req('parts'),env,'support')).status,200);assert.equal((await handle(req('finance'),env,'support')).status,200);assert.equal((await handle(req('stock',{id,request_id:id,delta:1,note:'Test'}),env,'support')).status,403);});

test('quotes accept existing numeric order IDs as well as UUIDs',async()=>{for(const order_id of [123,'123','9223372036854775807',id]){const calls=mock();const r=await handle(req('quote',{id,order_id,client:'Test',lines:[{kind:'labor',description:'Trabajo',quantity:1,unit_price:10,unit_cost:0}]}),env,'support');assert.equal(r.status,200);assert.equal(JSON.parse(calls.find(c=>c.url.includes('/rpc/')).init.body).p_order_id,order_id);}for(const order_id of ['bad','-1','9223372036854775808',9007199254740992]){mock();assert.equal((await handle(req('quote',{id,order_id,client:'Test',lines:[{kind:'labor',quantity:1,unit_price:10,unit_cost:0}]}),env,'support')).status,400);}});
