(function(){
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=v=>'USD '+Number(v||0).toFixed(2),label={labor:'Mano de obra',part:'Repuesto',service:'Servicio / costo externo'};
 const input=(name,title,value='',type='text',extra='')=>`<label>${title}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
 function download(name,rows){const csv=rows.map(row=>row.map(v=>'"'+String(typeof v==='string'&&/^[=+@\-]/.test(v)?"'"+v:v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function mount(host,options){
  const F=window.TSWorkshopFinance;let parts=[],data={quotes:[],lines:[],payments:[]},page=0,query='',mode=options.mode||'parts';
  const api=async(action,payload)=>{const headers=await options.headers();const r=await fetch(options.endpoint+(payload?'':'?action='+action),{method:payload?'POST':'GET',headers:{...headers,'Content-Type':'application/json'},...(payload?{body:JSON.stringify({action,...payload})}:{})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Error(d.error||'No se pudo consultar el servicio técnico.');return d;};
  host.innerHTML='<section class="wk"><p>Cargando datos de servicio técnico…</p></section>';
  const error=e=>{const el=host.querySelector('.wk-message');if(el)el.textContent=e.message;else host.innerHTML=`<section class="wk"><p role="alert">${esc(e.message)}</p><p>Comprueba la conexión y la migración V14.42.</p></section>`;};
  const formSubmit=(form,fn)=>{form.addEventListener('submit',async e=>{e.preventDefault();if(form.dataset.busy)return;form.dataset.busy='1';const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn(new FormData(form),e);}catch(err){const msg=form.querySelector('.wk-form-message');if(msg)msg.textContent=err.message;else error(err);}finally{delete form.dataset.busy;buttons.forEach(b=>b.disabled=false);}});};
  const dialog=(title,html)=>{host.querySelector('dialog')?.remove();const d=document.createElement('dialog');d.className='wk-dialog';d.innerHTML=`<h2>${esc(title)}</h2>${html}<button type="button" class="wk-secondary wk-close">Cerrar</button>`;host.querySelector('.wk').append(d);d.querySelector('.wk-close').onclick=()=>d.close();d.showModal();return d;};
  async function refresh(){
   if(mode==='parts'){parts=(await api('parts')).parts;renderParts();}
   else{data=await api('finance');if(mode==='summary')renderSummary();else{parts=(await api('parts')).parts;renderFinance();}}
  }
  function header(title,description){return `<section class="wk"><header><div><h2>${title}</h2><p>${description}</p></div><button type="button" class="wk-refresh">Actualizar</button></header><p class="wk-message" role="status"></p>`;}
  function baseEvents(){host.querySelector('.wk-refresh').onclick=()=>refresh().catch(error);}
  function renderParts(){
   const filtered=parts.filter(p=>[p.sku,p.name,p.category,p.compatible_models,p.catalog_details?.quality,p.catalog_details?.repair].join(' ').toLowerCase().includes(query.toLowerCase()));page=Math.min(page,Math.max(0,Math.ceil(filtered.length/40)-1));
   host.innerHTML=header('Repuestos de servicio técnico','Inventario exclusivo del taller. La web, el panel administrativo, Inventory y Soporte consultan estos mismos registros.')+`<div class="wk-actions"><input class="wk-search" aria-label="Buscar repuesto" placeholder="SKU, modelo, calidad o reparación" value="${esc(query)}"><button class="wk-new">Nuevo repuesto</button></div><p>${filtered.length} repuestos · página ${page+1} de ${Math.max(1,Math.ceil(filtered.length/40))}</p><div class="wk-scroll"><table><thead><tr><th>SKU / pieza</th><th>Modelo / calidad</th><th>Stock</th><th>Costo</th><th>Precio</th><th>Web</th><th>Acciones</th></tr></thead><tbody>${filtered.slice(page*40,page*40+40).map(p=>`<tr><td><b>${esc(p.sku)}</b><br>${esc(p.name)}${p.active?'':' · Inactivo'}</td><td>${esc(p.compatible_models)}<br>${esc(p.catalog_details?.quality)}</td><td>${Number(p.quantity)}<br><small>Mín. ${Number(p.minimum_stock)}</small></td><td>${p.unit_cost===null?'Sin registrar':money(p.unit_cost)}</td><td>${p.sale_price===null?'Consultar':money(p.sale_price)}</td><td>${p.published?'Publicado':'Oculto'}</td><td><button data-edit="${esc(p.id)}">Editar</button> <button data-stock="${esc(p.id)}">Movimiento</button></td></tr>`).join('')||'<tr><td colspan="7">No hay repuestos. Importa el catálogo inicial V14.42 o crea una pieza.</td></tr>'}</tbody></table></div><div class="wk-actions"><button class="wk-prev" ${page===0?'disabled':''}>Anterior</button><button class="wk-next" ${(page+1)*40>=filtered.length?'disabled':''}>Siguiente</button></div></section>`;
   baseEvents();host.querySelector('.wk-search').onchange=e=>{query=e.target.value;page=0;renderParts();};host.querySelector('.wk-new').onclick=()=>editPart();host.querySelector('.wk-prev').onclick=()=>{page--;renderParts();};host.querySelector('.wk-next').onclick=()=>{page++;renderParts();};host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editPart(parts.find(p=>p.id===b.dataset.edit)));host.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>stockPart(parts.find(p=>p.id===b.dataset.stock)));
  }
  function editPart(p={}){
   const m=p.catalog_details||{},id=p.id||crypto.randomUUID();const d=dialog(p.id?'Editar repuesto':'Nuevo repuesto',`<form><div class="wk-grid">${input('sku','SKU',p.sku,'text','required')}${input('name','Nombre',p.name,'text','required')}${input('category','Categoría (iPhone, Mac, iPad…)',p.category)}${input('compatible_models','Compatibilidad',p.compatible_models)}${input('unit_cost','Costo unitario USD',p.unit_cost??'','number','min="0" step="0.01"')}${input('sale_price','Precio del repuesto USD',p.sale_price??'','number','min="0" step="0.01"')}${input('minimum_stock','Stock mínimo',p.minimum_stock||0,'number','min="0" step="1" required')}${input('location','Ubicación',p.location)}${input('model','Modelo',m.model)}${input('series','Serie',m.series)}${input('model_type','Variante',m.model_type)}${input('repair','Reparación',m.repair)}${input('quality','Calidad',m.quality)}${input('image_url','URL HTTPS de imagen',m.image_url,'url')}${input('warranty','Garantía publicada',m.warranty)}${input('repair_time','Tiempo estimado',m.repair_time)}</div><label>Descripción<textarea name="description">${esc(m.description)}</textarea></label><label class="wk-check"><input type="checkbox" name="published" ${p.published?'checked':''}> Publicar en servicio técnico</label><label class="wk-check"><input type="checkbox" name="active" ${p.active!==false?'checked':''}> Activo</label><p>El stock se registra con Movimiento; no se mezcla con el inventario de equipos.</p><p class="wk-form-message" role="status"></p><button>Guardar repuesto</button></form>`);
   formSubmit(d.querySelector('form'),async f=>{const v=Object.fromEntries(f);await api('save_part',{part:{...v,id,minimum_stock:Number(v.minimum_stock),unit_cost:v.unit_cost===''?null:Number(v.unit_cost),sale_price:v.sale_price===''?null:Number(v.sale_price),active:f.has('active'),published:f.has('published'),catalog_details:Object.fromEntries(['model','series','model_type','repair','quality','image_url','description','warranty','repair_time'].map(k=>[k,v[k]||'']))}});d.close();await refresh();});
  }
  function stockPart(p){const requestId=crypto.randomUUID();const d=dialog('Movimiento · '+p.sku,`<form><p>${esc(p.name)} · Existencia: ${p.quantity}</p>${input('delta','Cantidad (+ entrada / − ajuste)',1,'number','step="1" required')}${input('note','Motivo o documento de compra','','text','required')}<p>Las ventas se descuentan al registrar el primer cobro. Usa este formulario para compras, apertura o correcciones.</p><p class="wk-form-message" role="status"></p><button>Registrar movimiento</button></form>`);formSubmit(d.querySelector('form'),async f=>{await api('stock',{id:p.id,request_id:requestId,delta:Number(f.get('delta')),note:f.get('note')});d.close();await refresh();});}
  function cards(r){return `<div class="wk-cards"><div><small>Cotizado</small><b>${money(r.quoted)}</b></div><div><small>Cobrado</small><b>${money(r.received)}</b></div><div><small>Mano de obra cobrada</small><b>${money(r.labor)}</b></div><div><small>Margen de repuestos cobrado</small><b>${money(r.partProfit)}</b></div><div><small>Margen de otros servicios</small><b>${money(r.serviceProfit)}</b></div><div><small>Margen total cobrado</small><b>${money(r.totalProfit)}</b></div></div>`;}
  function legacyNotice(){const groups={};for(const q of data.legacy_quotes||[]){const currency=q.quote_currency||'USD';groups[currency]=(groups[currency]||0)+Number(q.quote_amount);}return (data.legacy_quotes||[]).length?'<p><b>Presupuestos previos sin desglose:</b> '+Object.entries(groups).map(([c,v])=>esc(c)+' '+v.toFixed(2)).join(' · ')+'. Siguen en las órdenes originales; no tienen fecha de cotización ni cobros verificables para este informe.</p>':'';}
  function renderSummary(){const today=F.day(new Date()),r=F.summarize(data,today,today);host.innerHTML=header('Dinero del servicio técnico · hoy','Importes en USD. Solo cobros registrados; una cotización no se cuenta como dinero recibido.')+cards(r)+legacyNotice()+`<p>Para el detalle y reparto lunes–sábado abre Cobros y liquidación semanal. Los presupuestos antiguos sin desglose siguen en sus órdenes; no se inventan cobros históricos.</p></section>`;baseEvents();}
  function renderFinance(){
   const paid=q=>data.payments.filter(p=>p.quote_id===q.id).reduce((n,p)=>n+Number(p.amount),0);
   host.innerHTML=header('Cobros y liquidación semanal','Solo servicio técnico. Reparto de mano de obra cobrada: empresa 50%, Freddy 25%, Nelson 25%.')+`<div class="wk-actions"><button class="wk-quote">Nueva cotización / venta</button><button class="wk-report">Reporte lunes a sábado</button></div><div class="wk-summary"></div><h3>Cotizaciones y saldos</h3><div class="wk-scroll"><table><tr><th>Fecha / referencia</th><th>Cliente</th><th>Total cotizado</th><th>Cobrado</th><th>Saldo</th><th>Estado</th><th>Acciones</th></tr>${data.quotes.map(q=>`<tr><td>${F.day(q.quoted_at)}<br><small>${esc(q.id.slice(0,8))}</small></td><td>${esc(q.client_name)}</td><td>${money(q.total)}</td><td>${money(paid(q))}</td><td>${money(q.state==='cancelled'?0:Number(q.total)-paid(q))}</td><td>${esc({quoted:'Cotizado',posted:'Con cobros',cancelled:'Anulado'}[q.state])}</td><td><button data-detail="${q.id}">Detalle</button> ${q.state!=='cancelled'&&F.cents(Number(q.total)-paid(q))>0?`<button data-pay="${q.id}">Cobrar</button>`:''} ${data.can_report&&q.state==='quoted'?`<button data-cancel="${q.id}" class="wk-secondary">Anular</button>`:''}</td></tr>`).join('')||'<tr><td colspan="7">Sin cotizaciones desglosadas todavía.</td></tr>'}</table></div></section>`;
   baseEvents();const today=F.day(new Date());const currentWeek=F.monday(today),weekReport=F.summarize(data,currentWeek,F.addDays(currentWeek,5));host.querySelector('.wk-summary').innerHTML='<h3>Hoy · '+today+'</h3>'+cards(F.summarize(data,today,today))+'<h3>Acumulado registrado</h3>'+cards(F.summarize(data,'0001-01-01',today))+legacyNotice()+(data.can_report?'<h3>Semana actual · '+currentWeek+' al '+F.addDays(currentWeek,5)+'</h3>'+cards(weekReport)+'<p><b>Mano de obra:</b> Empresa '+money(weekReport.split.company)+' · Freddy '+money(weekReport.split.freddy)+' · Nelson '+money(weekReport.split.nelson)+'</p>':'');host.querySelector('.wk-quote').onclick=()=>newQuote();host.querySelector('.wk-report').onclick=()=>weeklyReport();host.querySelector('.wk-report').hidden=!data.can_report;
   host.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>newPayment(data.quotes.find(q=>q.id===b.dataset.pay)));
   host.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showQuote(data.quotes.find(q=>q.id===b.dataset.detail)));
   host.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{if(!confirm('¿Anular esta cotización sin cobros?'))return;try{await api('cancel_quote',{id:b.dataset.cancel});await refresh();}catch(e){error(e);}});
  }
  function newQuote(){
   const id=crypto.randomUUID(),lines=[];const d=dialog('Cotización desglosada',`<form><label>Orden<select name="order_id"><option value="">Venta directa de repuesto / servicio</option>${(data.orders||options.orders||[]).map(o=>`<option value="${esc(o.id)}">${esc(o.code)} · ${esc(o.client)}</option>`).join('')}</select></label>${input('client','Cliente','','text','required')}<div class="wk-actions"><button type="button" data-add="labor">+ Mano de obra</button><button type="button" data-add="part">+ Repuesto</button><button type="button" data-add="service">+ Otro servicio</button></div><div class="wk-lines"></div><p class="wk-total"></p><p>Los costos quedan guardados con la cotización. Los abonos se distribuyen proporcionalmente entre los conceptos; solo la mano de obra cobrada se reparte.</p><p class="wk-form-message" role="status"></p><button>Guardar cotización</button></form>`);
   const form=d.querySelector('form');form.elements.order_id.onchange=()=>{const o=(data.orders||options.orders||[]).find(x=>String(x.id)===form.elements.order_id.value);if(o)form.elements.client.value=o.client;};
   function draw(){d.querySelector('.wk-lines').innerHTML=lines.map((l,i)=>`<fieldset data-line="${i}"><legend>${label[l.kind]}</legend>${l.kind==='part'?`<label>Buscar repuesto<input data-search="${i}" placeholder="SKU o modelo"><select data-part="${i}"><option value="">Selecciona un repuesto</option>${parts.filter(p=>p.active).map(p=>`<option value="${p.id}" ${p.id===l.part_id?'selected':''}>${esc(p.sku)} · ${esc(p.name)} · Stock ${p.quantity}</option>`).join('')}</select></label>`:''}<div class="wk-grid">${input('description','Concepto',l.description,'text','required data-field="description"')}${input('quantity','Cantidad',l.quantity,'number','min="1" step="1" required data-field="quantity"')}${input('unit_price','Precio unitario USD',l.unit_price,'number','min="0" step="0.01" required data-field="unit_price"')}${input('unit_cost','Costo unitario USD',l.unit_cost??'','number',`min="0" step="0.01" required data-field="unit_cost" ${l.kind!=='service'?'readonly':''}`)}</div><button type="button" data-remove="${i}" class="wk-secondary">Quitar</button></fieldset>`).join('');
    d.querySelectorAll('[data-line]').forEach(field=>field.querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>{lines[Number(field.dataset.line)][el.dataset.field]=el.dataset.field==='description'?el.value:Number(el.value);total();}));
    d.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{lines.splice(Number(b.dataset.remove),1);draw();});
    d.querySelectorAll('[data-part]').forEach(sel=>sel.onchange=()=>{const p=parts.find(x=>x.id===sel.value),l=lines[Number(sel.dataset.part)];if(p){Object.assign(l,{part_id:p.id,description:p.name,unit_price:p.sale_price??0,unit_cost:p.unit_cost});draw();}});
    d.querySelectorAll('[data-search]').forEach(el=>el.oninput=()=>{const sel=d.querySelector(`[data-part="${el.dataset.search}"]`);for(const opt of sel.options)opt.hidden=!!opt.value&&!opt.text.toLowerCase().includes(el.value.toLowerCase());});total();
   }
   const total=()=>d.querySelector('.wk-total').textContent='Total: '+money(lines.reduce((n,l)=>n+l.quantity*Number(l.unit_price||0),0));
   d.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{lines.push({kind:b.dataset.add,description:'',part_id:null,quantity:1,unit_price:0,unit_cost:b.dataset.add==='part'?null:0});draw();});
   formSubmit(form,async f=>{if(!lines.length)throw Error('Añade al menos un concepto.');if(lines.some(l=>l.kind==='part'&&(!l.part_id||l.unit_cost===null)))throw Error('Selecciona el repuesto y registra primero su costo en el inventario técnico.');await api('quote',{id,order_id:f.get('order_id')||null,client:f.get('client'),lines});d.close();await refresh();});
  }
  function showQuote(q){const lines=data.lines.filter(l=>l.quote_id===q.id),payments=data.payments.filter(p=>p.quote_id===q.id);dialog('Detalle · '+q.client_name,`<div class="wk-scroll"><table><tr><th>Tipo</th><th>Concepto</th><th>Cant.</th><th>Precio</th><th>Costo</th><th>Total</th></tr>${lines.map(l=>`<tr><td>${label[l.kind]}</td><td>${esc(l.description)}</td><td>${l.quantity}</td><td>${money(l.unit_price)}</td><td>${money(l.unit_cost)}</td><td>${money(l.total)}</td></tr>`).join('')}</table></div><h3>Cobros registrados</h3>${payments.map(p=>`<p>${F.day(p.paid_at)} · ${money(p.amount)} · ${esc(p.method)} · ${esc(p.reference)}</p>`).join('')||'<p>Sin cobros.</p>'}`);}
  function newPayment(q){
   const id=crypto.randomUUID(),balance=Number(q.total)-data.payments.filter(p=>p.quote_id===q.id).reduce((n,p)=>n+Number(p.amount),0),today=F.day(new Date());
   const d=dialog('Registrar cobro · '+q.client_name,`<form><p>Saldo: ${money(balance)}. El primer cobro descuenta una sola vez todos los repuestos de esta cotización.</p><div class="wk-grid"><label>Moneda<select name="currency"><option>USD</option><option>VES</option></select></label>${input('original_amount','Importe recibido',balance.toFixed(2),'number','min="0.01" step="0.01" required')}${input('rate','Tasa VES por USD (USD: 1)',1,'number','min="0.000001" step="0.000001" required')}${input('date','Fecha del cobro',today,'date','required max="'+today+'"')}${input('time','Hora (Caracas)',new Date(Date.now()-4*3600000).toISOString().slice(11,16),'time','required')}${input('method','Método de pago','','text','required')}${input('reference','Referencia / comprobante')}</div><p class="wk-converted"></p><p>Confirma el dinero efectivamente recibido. Este registro no ejecuta un cobro bancario ni transfiere dinero a los socios.</p><p class="wk-form-message" role="status"></p><button>Confirmar cobro recibido</button></form>`);
   const form=d.querySelector('form'),amount=()=>Math.round(Number(form.elements.original_amount.value)/Number(form.elements.rate.value)*100)/100;
   form.oninput=()=>d.querySelector('.wk-converted').textContent='Equivalente: '+money(amount());form.elements.currency.onchange=()=>{if(form.elements.currency.value==='USD')form.elements.rate.value=1;form.oninput();};form.oninput();
   formSubmit(form,async f=>{await api('payment',{id,quote_id:q.id,amount:amount(),original_amount:Number(f.get('original_amount')),currency:f.get('currency'),rate:Number(f.get('rate')),paid_at:new Date(f.get('date')+'T'+f.get('time')+':00-04:00').toISOString(),method:f.get('method'),reference:f.get('reference')});d.close();await refresh();});
  }
  function weeklyReport(){
   const start=F.monday(F.day(new Date()));let report;
   const d=dialog('Liquidación · lunes a sábado',`<label>Semana del lunes<input class="wk-week" type="date" value="${start}"></label><div class="wk-weekly"></div><button class="wk-export">Exportar detalle CSV</button>`);
   const render=()=>{const from=F.monday(d.querySelector('.wk-week').value||start),to=F.addDays(from,5),sunday=F.addDays(from,6);d.querySelector('.wk-week').value=from;report=F.summarize(data,from,to);const extra=F.summarize(data,sunday,sunday);d.querySelector('.wk-weekly').innerHTML=`<p>${from} al ${to} · América/Caracas · según fecha de cobro</p>${cards(report)}<h3>Reparto de mano de obra cobrada</h3><div class="wk-cards"><div><small>Empresa · 50%</small><b>${money(report.split.company)}</b></div><div><small>Freddy · 25%</small><b>${money(report.split.freddy)}</b></div><div><small>Nelson · 25%</small><b>${money(report.split.nelson)}</b></div></div><p>Los márgenes de repuestos y otros servicios se muestran aparte y no participan en este reparto. Este reporte es un cálculo, no una constancia de pago a socios.</p><p><b>Domingo fuera del ciclo:</b> ${money(extra.received)} cobrado · mano de obra ${money(extra.labor)}. Se conserva en los registros, sin sumarlo a lunes–sábado.</p><h3>Detalle diario</h3><div class="wk-scroll"><table><tr><th>Día</th><th>Cotizado</th><th>Cobrado</th><th>Mano de obra</th><th>Margen repuestos</th><th>Margen otros servicios</th></tr>${report.daily.map(r=>`<tr><td>${r.date}</td><td>${money(r.quoted)}</td><td>${money(r.received)}</td><td>${money(r.labor)}</td><td>${money(r.partProfit)}</td><td>${money(r.serviceProfit)}</td></tr>`).join('')}</table></div><h3>Detalle por servicio y repuesto</h3><div class="wk-scroll"><table><tr><th>Fecha / cliente</th><th>Concepto</th><th>Tipo</th><th>Cobrado</th><th>Costo proporcional</th><th>Margen</th></tr>${report.details.map(r=>`<tr><td>${r.date}<br>${esc(r.client)}</td><td>${esc(r.description)}</td><td>${label[r.kind]}</td><td>${money(r.revenue)}</td><td>${money(r.cost)}</td><td>${money(r.profit)}</td></tr>`).join('')}</table></div><p>Abonos: ingresos y costos se reconocen en proporción al importe cobrado. El margen no descuenta gastos generales del negocio.</p>`;};
   d.querySelector('.wk-week').onchange=render;render();d.querySelector('.wk-export').onclick=()=>download('liquidacion-tecnica-'+d.querySelector('.wk-week').value+'.csv',[['Semana',d.querySelector('.wk-week').value],['Empresa 50%',report.split.company],['Freddy 25%',report.split.freddy],['Nelson 25%',report.split.nelson],[],['Fecha','Cliente','Cotización','Cobro','Concepto','Tipo','Cobrado USD','Costo USD','Margen USD','Método','Referencia'],...report.details.map(r=>[r.date,r.client,r.quote,r.payment,r.description,label[r.kind],r.revenue.toFixed(2),r.cost.toFixed(2),r.profit.toFixed(2),r.method,r.reference])]);
  }
  try{await refresh();}catch(e){error(e);}
 }
 window.TSWorkshop={mount};
})();
