const reply=(statusCode,body)=>({statusCode,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'POST, OPTIONS'},body:JSON.stringify(body)});
const clean=v=>String(v??'').trim();
const esc=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
exports.handler=async event=>{
  if(event.httpMethod==='OPTIONS')return reply(200,{ok:true});if(event.httpMethod!=='POST')return reply(405,{ok:false,error:'Método no permitido'});
  const url=clean(process.env.SUPPORT_SUPABASE_URL||process.env.SUPABASE_URL).replace(/\/$/,'');const key=clean(process.env.SUPPORT_SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY);
  if(!url||!key)return reply(501,{ok:false,error:'Faltan las variables de Supabase de Soporte en Netlify'});
  try{
    const token=clean(event.headers.authorization||event.headers.Authorization).replace(/^Bearer\s+/i,'');if(!token)return reply(401,{ok:false,error:'Sesión requerida'});
    const ur=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${token}`}});const user=await ur.json().catch(()=>({}));if(!ur.ok||!user.email)return reply(401,{ok:false,error:'Sesión inválida'});
    const h={apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};const req=async(path,options={})=>{const r=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{...h,...(options.headers||{})}});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||`Error ${r.status}`);return d};
    const profiles=await req(`service_users?select=*&email=ilike.${encodeURIComponent(user.email)}&limit=1`);const profile=profiles?.[0];if(!profile||profile.activo===false)return reply(403,{ok:false,error:'Usuario de soporte no autorizado'});
    const body=JSON.parse(event.body||'{}');if(clean(body.action)!=='notify_client')return reply(400,{ok:false,error:'Acción no válida'});
    const rows=await req(`service_orders?select=*&id=eq.${encodeURIComponent(clean(body.order_id))}&limit=1`);const o=rows?.[0];if(!o)return reply(404,{ok:false,error:'Orden no encontrada'});if(!o.client_email)return reply(400,{ok:false,error:'La orden no tiene correo del cliente'});
    const resend=clean(process.env.RESEND_API_KEY||process.env.RESEND_APY_KEY);if(!resend)return reply(501,{ok:false,error:'Falta RESEND_API_KEY en el sitio de Soporte'});
    const tracking=`https://soporte.thinkstore.com.ve/?orden=${encodeURIComponent(o.code)}`;const subject=`ThinkStore Soporte — ${o.status} | ${o.code}`;
    const html=`<div style="background:#f5f5f7;padding:30px;font-family:Arial;color:#1d1d1f"><div style="max-width:650px;margin:auto;background:white;border-radius:24px;overflow:hidden"><div style="background:#09090c;color:white;padding:28px;text-align:center"><h1>ThinkStore Soporte</h1><p>${esc(o.code)}</p></div><div style="padding:28px"><p>Hola <b>${esc(o.client_name)}</b>,</p><p>Tu equipo <b>${esc(o.device_model)}</b> fue actualizado.</p><div style="background:#f1f3f5;border-radius:16px;padding:18px"><b>Estado:</b> ${esc(o.status)}<br><b>Presupuesto:</b> ${esc(o.quote_status||'Pendiente')}${o.quote_amount?` · ${esc(o.quote_currency||'USD')} ${Number(o.quote_amount).toFixed(2)}`:''}<br><b>Guía:</b> ${esc(o.tracking_code||'No asignada')}</div><p style="text-align:center;margin-top:26px"><a href="${tracking}" style="background:#111;color:#fff;padding:13px 22px;border-radius:999px;text-decoration:none">Consultar orden</a></p></div></div></div>`;
    const er=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${resend}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.FROM_SOPORTE_EMAIL||process.env.FROM_EMAIL||'ThinkStore Soporte <soporte@thinkstore.com.ve>',to:o.client_email,reply_to:process.env.REPLY_TO_SOPORTE||'soporte@thinkstore.com.ve',subject,html,text:`Hola ${o.client_name}. Tu orden ${o.code} está en estado: ${o.status}. Consulta: ${tracking}`})});const ed=await er.json().catch(()=>({}));if(!er.ok)throw new Error(ed.message||'Error enviando correo');
    await req('service_audit_log',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({actor_email:user.email,actor_role:profile.rol,action:'notify_client',entity_type:'service_order',entity_id:String(o.id),after_data:{recipient:o.client_email,provider_id:ed.id||null,status:o.status}})});
    return reply(200,{ok:true,email:{sent:true,id:ed.id||null}});
  }catch(error){console.error('Support actions',error);return reply(500,{ok:false,error:error.message||'Error interno'})}
};
